/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ServicoDAO;
import DTO.ServiçoDTO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author icaro
 */
public class Alterações_servicos extends javax.swing.JFrame {

    /**
     * Creates new form Alterações_servicos
     */
    public Alterações_servicos() {
        initComponents();
        listarValoresServico();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(Login.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jtitulo = new javax.swing.JLabel();
        jnome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jvalor = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        bsalvar = new javax.swing.JButton();
        balterar = new javax.swing.JButton();
        bconsultar = new javax.swing.JButton();
        bexcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServico = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtitulo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jtitulo.setText("CADASTRO SERVIÇOS");

        jnome.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jnome.setText("NOME:");

        jvalor.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jvalor.setText("VALOR:");

        bsalvar.setText("SALVAR");
        bsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalvarActionPerformed(evt);
            }
        });

        balterar.setText("ALTERAR");

        bconsultar.setText("CONSULTAR");
        bconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconsultarActionPerformed(evt);
            }
        });

        bexcluir.setText("EXCLUIR");

        tabelaServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Serviço", "Nome ", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tabelaServico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balterar)
                        .addGap(30, 30, 30)
                        .addComponent(bconsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bexcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jnome)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jvalor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnome)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jvalor))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsalvar)
                    .addComponent(balterar)
                    .addComponent(bconsultar)
                    .addComponent(bexcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void bsalvarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String nome_servico=txtnome.getText();
        Double valor_servico=Double.parseDouble(txtvalor.getText());
        
        ServiçoDTO objservicodto=new ServiçoDTO();
        objservicodto.setNome_servico(nome_servico);
        objservicodto.setValor_servico(valor_servico);

        
        ServicoDAO objservicodao=new ServicoDAO();
        objservicodao.inserirServico(objservicodto);

    }                                       

    private void bconsultarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        listarValoresServico();
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterações_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterações_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterações_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterações_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alterações_servicos().setVisible(true);
            }
        });
    }
  private void listarValoresServico(){
               
                   ServicoDAO objetoClienteDAO=new ServicoDAO();
                   DefaultTableModel model=(DefaultTableModel)tabelaServico.getModel();
                   model.setNumRows(0);
                   ArrayList<ServiçoDTO> lista=objetoClienteDAO.pesquisarServico();
                   
                   for(int num=0;num<lista.size();num++){
                       model.addRow(new Object[]{
                           lista.get(num).getId_servico(),
                           lista.get(num).getNome_servico(),
                           lista.get(num).getValor_servico(),
                       });
                   }
            
               }
           
    // Variables declaration - do not modify                     
    private javax.swing.JButton balterar;
    private javax.swing.JButton bconsultar;
    private javax.swing.JButton bexcluir;
    private javax.swing.JButton bsalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jnome;
    private javax.swing.JLabel jtitulo;
    private javax.swing.JLabel jvalor;
    private javax.swing.JTable tabelaServico;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration                   
}
