
package View;


import DAO.ClienteDAO;
import DTO.ClienteDTO;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    int xMouse,yMouse;
      
    public Login() {
        initComponents();       
        setLocationRelativeTo(null);
        setDefaultCloseOperation(Login.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        cabelobg = new javax.swing.JLabel();
        ltitulo = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        bsair = new javax.swing.JPanel();
        tsair = new javax.swing.JLabel();
        lusuario = new javax.swing.JLabel();
        tusuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lsenha = new javax.swing.JLabel();
        tsenha = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        blogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/WhatsApp Image 2022-08-08 at 19.45.26.jpeg"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, -1));

        cabelobg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Captura de tela 2022-08-08 192505 .png"))); // NOI18N
        background.add(cabelobg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        ltitulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        ltitulo.setForeground(new java.awt.Color(0, 0, 0));
        ltitulo.setText("INICIAR SESSÃO");
        background.add(ltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        bsair.setBackground(new java.awt.Color(255, 255, 255));

        tsair.setBackground(new java.awt.Color(255, 255, 255));
        tsair.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        tsair.setForeground(new java.awt.Color(0, 0, 0));
        tsair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tsair.setText("X");
        tsair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tsair.setPreferredSize(new java.awt.Dimension(40, 40));
        tsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tsairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tsairMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bsairLayout = new javax.swing.GroupLayout(bsair);
        bsair.setLayout(bsairLayout);
        bsairLayout.setHorizontalGroup(
            bsairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tsair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        bsairLayout.setVerticalGroup(
            bsairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bsairLayout.createSequentialGroup()
                .addComponent(tsair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(bsair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 736, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(bsair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        lusuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lusuario.setForeground(new java.awt.Color(0, 0, 0));
        lusuario.setText("USUÁRIO:");
        background.add(lusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        tusuario.setBackground(new java.awt.Color(255, 255, 255));
        tusuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tusuario.setForeground(new java.awt.Color(204, 204, 204));
        tusuario.setText("Digite seu usuário");
        tusuario.setBorder(null);
        tusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tusuarioMousePressed(evt);
            }
        });
        tusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusuarioActionPerformed(evt);
            }
        });
        background.add(tusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 420, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 420, 10));

        lsenha.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lsenha.setForeground(new java.awt.Color(0, 0, 0));
        lsenha.setText("SENHA:");
        background.add(lsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        tsenha.setBackground(new java.awt.Color(255, 255, 255));
        tsenha.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tsenha.setForeground(new java.awt.Color(204, 204, 204));
        tsenha.setText("********");
        tsenha.setBorder(null);
        tsenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tsenhaMousePressed(evt);
            }
        });
        background.add(tsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 420, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 420, 10));

        blogin.setBackground(new java.awt.Color(0, 0, 0));
        blogin.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        blogin.setForeground(new java.awt.Color(255, 255, 255));
        blogin.setText("ENTRAR");
        blogin.setBorder(null);
        blogin.setBorderPainted(false);
        blogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        background.add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void headerMousePressed(java.awt.event.MouseEvent evt) {                                    
        xMouse = evt.getX();
        yMouse = evt.getY();
    }                                   

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {                                    
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();       
        this.setLocation(x - xMouse,y - yMouse);
    }                                   

    private void tsairMouseClicked(java.awt.event.MouseEvent evt) {                                   
       System.exit(0);
    }                                  

    private void tsairMouseEntered(java.awt.event.MouseEvent evt) {                                   
        tsair.setBackground(Color.RED);
        bsair.setBackground(Color.RED);      
    }                                  

    private void tsairMouseExited(java.awt.event.MouseEvent evt) {                                  
        tsair.setBackground(Color.WHITE);
        tsair.setBackground(Color.BLACK);
        bsair.setBackground(Color.WHITE);
    }                                 

    private void tusuarioMousePressed(java.awt.event.MouseEvent evt) {                                      
       if(tusuario.getText().equals("Digite seu usuário")){
         tusuario.setText("");
         tusuario.setForeground(Color.BLACK);
        }
       if(String.valueOf(tsenha.getPassword()).isEmpty()){
         tsenha.setText("********");
         tsenha.setForeground(Color.gray);
        }
    }                                     

    private void tsenhaMousePressed(java.awt.event.MouseEvent evt) {                                    
       if(String.valueOf(tsenha.getPassword()).equals("********")){
         tsenha.setText("");
         tsenha.setForeground(Color.BLACK);
        }
       if(tusuario.getText().isEmpty()){
         tusuario.setText("Digite seu usuário");
         tusuario.setForeground(Color.GRAY);
    }
    }                                   

    private void tusuarioActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {                                       
     //tusuario tsenha
            try {
            String nome_cliente=tusuario.getText();
            String senha_cliente=tsenha.getText();

            ClienteDTO objclientedto=new ClienteDTO();
            objclientedto.setNome_usuario(nome_cliente);
            objclientedto.setSenha_usuario(senha_cliente);

            ClienteDAO objclientedao=new ClienteDAO();
            ResultSet rclientedao=objclientedao.autenticacaoUsuario(objclientedto);

            if(rclientedao.next()){
               MenuPrincipal mp = new MenuPrincipal();  
               mp.setVisible(true);
               dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Usuário ou senha invalida!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Login: " + e);
        }

    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel background;
    private javax.swing.JButton blogin;
    private javax.swing.JPanel bsair;
    private javax.swing.JLabel cabelobg;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel lsenha;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JLabel lusuario;
    private javax.swing.JLabel tsair;
    private javax.swing.JPasswordField tsenha;
    private javax.swing.JTextField tusuario;
    // End of variables declaration                   


}
